### ISSUE TITLE
Deep log inspection

### ISSUE THREAD

**Issue by loleg** [Streetwise/streetwise-app#11]
I've installed Timber.io to monitor our production environment. It has a [Python library](https://docs.timber.io/setup/languages/python) for profiling log entries. Determine if this adds benefit and if so, propose a deployment in a PR.

**Comment by yudistrange** [comment]
I guess this will be useful. The only other way to access logs is via heroku console / portal, which I think is truncating older logs. 

It will definitely be useful to have a place where we can access historical logs.

**Comment by yudistrange** [comment]
@loleg can you assign this issue to my?

**Comment by yudistrange** [comment]
The integration is complete. I am able to get logs from both stage and prod on the timber dashboard.

I have set up some rudimentary alerts as well. But they aren't tied to any communication. We can either do mails or slack. I was thinking that slack maybe a better alternative of the two.

Thoughts @loleg

**Comment by loleg** [comment]
Let's go with Slack.

**Comment by loleg** [comment]
Thanks for setting up Coralogix. Working good.
