### ISSUE TITLE
Postgres deprecation warning

### ISSUE THREAD

**Issue by loleg** [Streetwise/streetwise-app#16]
Probably nothing for us to do, but running the tests today gives me this warning:

```
================================== warnings summary ==================================
tests/test_api.py::test_vote_count
  /home/oleg/.cache/pypoetry/virtualenvs/streetwise-app-wUyb69jI-py3.7/lib64/python3.7/site-packages/sqlalchemy/util/langhelpers.py:253: SADeprecationWarning: The 'postgres' dialect name has been renamed to 'postgresql'
    loader = self.auto_fn(name)
```

**Comment by yudistrange** [comment]
It feels like this is related to your virtual env. 
Check out this issue: https://github.com/Kinto/kinto/issues/1905
It states that you need to remove psycopg2 from your venv.

**Comment by Natim** [comment]
I think the change you are talking about is related to https://github.com/Kinto/kinto/commit/8809f6b67c8aeeec8adbe126a21fc02e6582d655

**Comment by loleg** [comment]
Thank you @Natim @yudistrange for your pointers. I'm no longer seeing this in the logs or in CI or even in my local test runner. Looks like it was just an intermittent issue.
