### ISSUE TITLE
Occasional exceptions in the /api/vote API

### ISSUE THREAD

**Issue by yudistrange** [Streetwise/streetwise-app#27]
We are getting exceptions in the /api/vote API occasionally. This is followed by the message `Background on this error at: http://sqlalche.me/e/9h9h`

We need to dig deeper to understand what's the root cause of this.

**Comment by yudistrange** [comment]
The exception is being caused by too long a value for the agent_string in sessions table.
Relevant error log:

> 2020-05-25T07:59:52.047890+00:00 heroku[router]: at=info method=POST path="/api/vote/" host=streetwise-app.ch request_id=b947f480-855a-4200-8a8b-f9f3d18edc8d fwd="178.197.228.54,162.158.88.41" dyno=web.1 connect=1ms service=145ms status=500 bytes=266 protocol=https
> 2020-05-25T07:59:52.049509+00:00 app[web.1]: 10.97.20.110 - - [25/May/2020:07:59:52 +0000] "POST /api/vote/ HTTP/1.1" 500 37 "https://streetwise-app.ch/" "Mozilla/5.0 (Linux; Android 10; LYA-L29 Build/HUAWEILYA-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.186 Mobile Safari/537.36 Instagram 138.0.0.28.117 Android (29/10; 640dpi; 1440x2860; HUAWEI; LYA-L29; HWLYA; kirin980; de_CH; 210180523)"
> 2020-05-25T07:59:56.858870+00:00 app[web.1]: [2020-05-25 07:59:56,845] ERROR in app: Exception on /api/vote/ [POST]
> 2020-05-25T07:59:56.858878+00:00 app[web.1]: Traceback (most recent call last):
> 2020-05-25T07:59:56.858878+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
> 2020-05-25T07:59:56.858879+00:00 app[web.1]: cursor, statement, parameters, context
> 2020-05-25T07:59:56.858879+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
> 2020-05-25T07:59:56.858880+00:00 app[web.1]: cursor.execute(statement, parameters)
> 2020-05-25T07:59:56.858880+00:00 app[web.1]: psycopg2.errors.StringDataRightTruncation: value too long for type character varying(256)
> 2020-05-25T07:59:56.858881+00:00 app[web.1]:
> 2020-05-25T07:59:56.858881+00:00 app[web.1]:
> 2020-05-25T07:59:56.858882+00:00 app[web.1]: The above exception was the direct cause of the following exception:
> 2020-05-25T07:59:56.858882+00:00 app[web.1]:
> 2020-05-25T07:59:56.858882+00:00 app[web.1]: Traceback (most recent call last):
> 2020-05-25T07:59:56.858883+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
> 2020-05-25T07:59:56.858883+00:00 app[web.1]: rv = self.dispatch_request()
> 2020-05-25T07:59:56.858884+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
> 2020-05-25T07:59:56.858884+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
> 2020-05-25T07:59:56.858884+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
> 2020-05-25T07:59:56.858885+00:00 app[web.1]: resp = resource(*args, **kwargs)
> 2020-05-25T07:59:56.858885+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_limiter/extension.py", line 600, in __inner
> 2020-05-25T07:59:56.858886+00:00 app[web.1]: return obj(*a, **k)
> 2020-05-25T07:59:56.858886+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/views.py", line 89, in view
> 2020-05-25T07:59:56.858887+00:00 app[web.1]: return self.dispatch_request(*args, **kwargs)
> 2020-05-25T07:59:56.858887+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
> 2020-05-25T07:59:56.858887+00:00 app[web.1]: resp = meth(*args, **kwargs)
> 2020-05-25T07:59:56.858888+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask_restplus/marshalling.py", line 243, in wrapper
> 2020-05-25T07:59:56.858888+00:00 app[web.1]: resp = f(*args, **kwargs)
> 2020-05-25T07:59:56.858889+00:00 app[web.1]: File "/app/streetwise/api/votes.py", line 99, in post
> 2020-05-25T07:59:56.858889+00:00 app[web.1]: db.session.commit()
> 2020-05-25T07:59:56.858889+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
> 2020-05-25T07:59:56.858890+00:00 app[web.1]: return getattr(self.registry(), name)(*args, **kwargs)
> 2020-05-25T07:59:56.858890+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
> 2020-05-25T07:59:56.858891+00:00 app[web.1]: self.transaction.commit()
> 2020-05-25T07:59:56.858891+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 503, in commit
> 2020-05-25T07:59:56.858891+00:00 app[web.1]: self._prepare_impl()
> 2020-05-25T07:59:56.858892+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
> 2020-05-25T07:59:56.858892+00:00 app[web.1]: self.session.flush()
> 2020-05-25T07:59:56.858893+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
> 2020-05-25T07:59:56.858893+00:00 app[web.1]: self._flush(objects)
> 2020-05-25T07:59:56.858893+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
> 2020-05-25T07:59:56.858894+00:00 app[web.1]: transaction.rollback(_capture_exception=True)
> 2020-05-25T07:59:56.858894+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
> 2020-05-25T07:59:56.858894+00:00 app[web.1]: exc_value, with_traceback=exc_tb,
> 2020-05-25T07:59:56.858895+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
> 2020-05-25T07:59:56.858895+00:00 app[web.1]: raise exception
> 2020-05-25T07:59:56.858895+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
> 2020-05-25T07:59:56.858895+00:00 app[web.1]: flush_context.execute()
> 2020-05-25T07:59:56.858896+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
> 2020-05-25T07:59:56.858896+00:00 app[web.1]: rec.execute(self)
> 2020-05-25T07:59:56.858896+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
> 2020-05-25T07:59:56.858897+00:00 app[web.1]: uow,
> 2020-05-25T07:59:56.858897+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
> 2020-05-25T07:59:56.858897+00:00 app[web.1]: insert,
> 2020-05-25T07:59:56.858898+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
> 2020-05-25T07:59:56.858898+00:00 app[web.1]: statement, params
> 2020-05-25T07:59:56.858898+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 984, in execute
> 2020-05-25T07:59:56.858899+00:00 app[web.1]: return meth(self, multiparams, params)
> 2020-05-25T07:59:56.858916+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
> 2020-05-25T07:59:56.858916+00:00 app[web.1]: return connection._execute_clauseelement(self, multiparams, params)
> 2020-05-25T07:59:56.858917+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
> 2020-05-25T07:59:56.858917+00:00 app[web.1]: distilled_params,
> 2020-05-25T07:59:56.858917+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
> 2020-05-25T07:59:56.858924+00:00 app[web.1]: e, statement, parameters, cursor, context
> 2020-05-25T07:59:56.858924+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
> 2020-05-25T07:59:56.858925+00:00 app[web.1]: sqlalchemy_exception, with_traceback=exc_info[2], from_=e
> 2020-05-25T07:59:56.858925+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
> 2020-05-25T07:59:56.858925+00:00 app[web.1]: raise exception
> 2020-05-25T07:59:56.858925+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
> 2020-05-25T07:59:56.858926+00:00 app[web.1]: cursor, statement, parameters, context
> 2020-05-25T07:59:56.858926+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
> 2020-05-25T07:59:56.858926+00:00 app[web.1]: cursor.execute(statement, parameters)
> 2020-05-25T07:59:56.858927+00:00 app[web.1]: sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(256)
> 2020-05-25T07:59:56.858927+00:00 app[web.1]:
> 2020-05-25T07:59:56.858928+00:00 app[web.1]: [SQL: INSERT INTO sessions (created, hash, campaign_id, agent_address, agent_platform, agent_browser, agent_version, agent_string, agent_width, agent_height, is_complete) VALUES (CURRENT_TIMESTAMP, %(hash)s, %(campaign_id)s, %(agent_address)s, %(agent_platform)s, %(agent_browser)s, %(agent_version)s, %(agent_string)s, %(agent_width)s, %(agent_height)s, %(is_complete)s) RETURNING sessions.id]
> 2020-05-25T07:59:56.858928+00:00 app[web.1]: [parameters: {'hash': '5abbdb4f717ebe3e3863caf64dcb88f5', 'campaign_id': 1, 'agent_address': '10.33.39.40', 'agent_platform': 'android', 'agent_browser': 'chrome', 'agent_version': '74.0.3729.186', 'agent_string': 'Mozilla/5.0 (Linux; Android 10; LYA-L29 Build/HUAWEILYA-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.186 Mobile Safari/537.36 Instagram 138.0.0.28.117 Android (29/10; 640dpi; 1440x2860; HUAWEI; LYA-L29; HWLYA; kirin980; de_CH; 210180523)', 'agent_width': 360, 'agent_height': 667, 'is_complete': False}]
> 2020-05-25T07:59:56.858929+00:00 app[web.1]: (Background on this error at: http://sqlalche.me/e/9h9h)

**Comment by loleg** [comment]
Thanks for checking in on this. Please PR a migration to a larger column size.

**Comment by yudistrange** [comment]
This has been merged into master. Closing the issue.
