### ISSUE TITLE
Show the crowdsourcing goals

### ISSUE THREAD

**Issue by loleg** [Streetwise/streetwise-app#3]
Add a goal (and stretch goals?) to the image total count API, and show in the app (home page, user form, ..) an indicator of how far we are in the total crowdsourcing process to motivate the user to contribute.

**Comment by yudistrange** [comment]
Do we have the some designs for this component?

**Comment by loleg** [comment]
Yes, there's a sketch in the 3rd screen of https://streetwise-app.ch/#/tour

**Comment by loleg** [comment]
This is continued as part of PR #20

**Comment by loleg** [comment]
Please see my refactoring of your component in the PR:
- Slightly changed the name to reflect functionality
- Removed all words, German or otherwise
- Added a [Vuesax component](https://lusaxweb.github.io/vuesax/components/progress.html)
- Tidied up the code a bit

I wonder how performant that row counter call is. Should we store it in memory, updating every few hours?

**Comment by yudistrange** [comment]
I think we should cache this nevertheless. Saving it in app memory works for now.

However if we ever do a multi-dyno deploy, we may end up running into situations where the two app instances have different values cached. But let's solve for that once we cross that bridge.

**Comment by yudistrange** [comment]
I will also close #19

**Comment by loleg** [comment]
I think we can close this now, and add a separate ticket for a performance review.
