### ISSUE TITLE
Improvements to export API

### ISSUE THREAD

**Issue by loleg** [Streetwise/streetwise-app#30]
Expand the API with a full export that includes:

- Image name
- Coordinates
- Demographics of the session
- Mobile / desktop
- Screen ratio

**Comment by colombmo** [comment]
If possible also the Mapillary sequence ID and/or the Mapillary image ID could be added to this list. So we would have for each vote:
- Left image name
- Coordinates of left image
- Mapillary Sequence ID / Mapillary image ID for left image
- Right image name
- Coordinates of right image
- Mapillary sequence ID / Mapillary image ID for right image
- Winner (left, right, undecided)
- Demographics of the session
- Mobile / desktop
- Screen ratio

**Comment by loleg** [comment]
Refactored APIs available in #34

**Comment by colombmo** [comment]
The images' filename in /results/* is missing:
For example now there is 

`"left_image": {
            "id": 4381,
            "key": "QVVK5rubnofy2R4lUdY5-g",
            "seq": "hz03nbywe4xnr87r7wiu6i",
            "lat": 47.568192,
            "lon": 8.9036407
        }`

And we want
`"left_image": {
            "id": 4381,
            "filename": "img5840.jpg",
            "key": "QVVK5rubnofy2R4lUdY5-g",
            "seq": "hz03nbywe4xnr87r7wiu6i",
            "lat": 47.568192,
            "lon": 8.9036407
        }`

**Comment by loleg** [comment]
Added in #34 by @yudistrange
