### ISSUE TITLE
manifest.json is never served on stage or prod

### ISSUE THREAD

**Issue by yudistrange** [Streetwise/streetwise-app#35]
https://streetwise-stage.herokuapp.com/manifest.json

http://streetwise-app.ch/manifest.json

Possible root cause is misconfiguration in our gunicorn webserver which is disallowing it to serve manifest.json even though it's present in the dist directory.

Steps to replicate this locally:
1. `yarn build`
2. `flask run`
3. `curl localhost:5000/manifest.json`

It's worth noting that manifest.json is served fine when we serve frontend matter by `yarn serve` locally

**Comment by loleg** [comment]
We don't really configure gunicorn, except in the `Procfile`: it just serves what the Flask app decides to serve. Currently we only serve the Vue-compiled static files from `dist/static` in `streetwise/__init__.py`, but manifest.json is in `dist`. We need to specify that Flask should serve it as well.

**Comment by loleg** [comment]
Looking good. I think we can close this: just one question, does this have implications on our mobile device support, i.e. needs retesting?

**Comment by yudistrange** [comment]
So the manifest is getting served fine. The app works fine as a webpage on the mobile.

However if the app is installed as a progressive web app, the manifest changes are not reflected after a new deploy. I had to reinstall the PWA to see the newer changes.

**Comment by loleg** [comment]
Sounds great, closing.
