### ISSUE TITLE
Ad-blockers mistakenly ban our analytics script

### ISSUE THREAD

**Issue by yudistrange** [Streetwise/streetwise-app#36]
We are injecting the url for fathom-analytics/3.js in our head tag. This is getting rejected by some ad-blockers as a possible CORS issue. 

If we can bundle the fathom analytics code with ours that would be great.

**Comment by loleg** [comment]
Response from the Fathom support team:

> Since Fathom doesn't track any personal details, we feel being blocked isn't necessary. That said, If you don't use our custom domains and block our script, then blocking it once blocks it on any site with Fathom. Your users can do the same.
> 
> If people want to be tracked, use our custom domain, and that will get around it.

**Comment by loleg** [comment]
@yudistrange could you check if/why not Fathom is being loaded in prod? Misconfigured environment?

**Comment by yudistrange** [comment]
Yep this was it. The config var was misconfigured. I have fixed that. The next deploy should take care of this.
