### ISSUE TITLE
Global progress bar CSS issues

### ISSUE THREAD

**Issue by colombmo** [Streetwise/streetwise-app#39]
- 14613 von 50'000 is partially on the progress bar and partially out of it on pc. On the smartphone too, but it’s more on the bar than out of it (see attached picture for the pc view).
![Screenshot 2020-05-29 at 14 43 28](https://user-images.githubusercontent.com/3964231/83267554-ac06a500-a1c4-11ea-95c7-3a6edfadbf61.jpg)

- And it should maybe be “14'613 von 50'000”, both with the ‘, or “14613 von 50000", both without ’, for consistency.

**Comment by yudistrange** [comment]
Also the progress bar will overlay on the text

![Screen Shot 2020-06-03 at 4 33 17 PM](https://user-images.githubusercontent.com/2247412/83630091-dc7d8300-a5b8-11ea-92f2-208d4f0031e2.png)

**Comment by yudistrange** [comment]
Shall I close this? We pushed a change to move the overlay text below the progress bar.
